config/routes.rb
Rails.application.routes.draw do
  root               'static_pages#home'
  get 'guide'     => 'static_pages#guide'
  get 'contact'   => 'static_pages#contact'
  get 'developer'     => 'static_pages#developer'

  # allows the error pages to be displayed for any type of request
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'dashboard' => 'users#show'

  resources :tutorials
  devise_for :users
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  TOPICS = [
    "Internet Basics",
    "Computer Basics",
    "Music & Entertainment",
    "Family & Friends",
    "Finances & Money",
    "Government & Licenses"
  ]

 def self.search(search)
    if search
      where("title LIKE ? OR tagline LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      find(:all)
    end
 end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tutorials

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  private
  def require_login
    unless user_signed_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_user_registration_url # halts request cycle
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if params[:search]
      @tutorials = Tutorial.search(params[:search]).order("created_at DESC")
    else
      @tutorials = Tutorial.all.order('created_at DESC')
    end
  end

  def guide
  end

  def contact
  end

  def developer
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :update, :destroy]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @suggestions = Tutorial.first(3)
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
    @user = current_user
  end

  # GET /tutorials/1/edit
  def edit
    @tutorial = Tutorial.find(params[:id])
    @user = current_user
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = current_user.tutorials.build(tutorial_params)
    @user = current_user

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    # only users who have created the tutorial can delete or admins
    @user = current_user
    if @tutorial.user_id == @user.id || @user.admin == true
      @tutorial.destroy
      respond_to do |format|
        format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
      @tutorial.increment!(:impressions, by = 1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      params.require(:tutorial).permit(:title, :tagline, :content, :author, :organization)
    end

    def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_user_registration_url # halts request cycle
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_login

  def show
    @user = current_user
    @tutorials = @user.tutorials
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/layouts/_footer.html.erb
<footer class="mobile-bottom">
  <div class="container">
    <div class="row" id="footer-text-center">
      <div class="col-sm-4">
        <h4>Navigation</h4>
        <%= link_to "Home",                     root_path %>
        <br>
        <%= link_to "Tutorial Creation Guide",  "/guide" %>
        <br>
        <%= link_to "Contact Us",               "/contact" %>
        <br>
        <%= link_to "Developers",               "/developer" %>
      </div>
      <div class="col-sm-4">
        <h4>Become a Contributor</h4>
        <% if user_signed_in? %>
          <div class="flex-column">
          <%= link_to 'Dashboard', dashboard_path %>
          <%= link_to 'Edit profile', edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <div class="flex-column">
          <%= link_to "Create Contributor Account", new_user_registration_path %>
          <%= link_to "Login as a Contributor", new_user_session_path %>
          </div>
        <% end %>
      </div>
      <div class="col-sm-4">
      <% if user_signed_in? %>
        <h4>How to Help</h4>
        <%= link_to "Create a Tutorial", new_tutorial_path, class: "btn btn-danger" %>
      <% end %>
    </div>
    <div class="row"></div>
      <div class="col-sm-12 text-center">
        <br>
        Made with <i class="glyphicon glyphicon-heart"></i> in San Francisco, CA
        <br>
          <small>Hosted by <a href="https://www.heroku.com/" target="_blank">Heroku</a></small>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">GoDigitalWith.Us</a>      
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav top-nav">
      <li><a href="/">Home</a></li>
      <li><a href="/contact">Contact Us</a></li>
    </ul>

    <%= form_tag(root_path, :method => "get", id: "search-form", class: "input-group searchbar") do %>
      <%= text_field_tag :search, params[:search], class: "form-control search", autofocus: true, placeholder: "Search Tutorials" %>
      <div class="input-group-btn">
        <%= button_tag(type: "submit", class: "search primary-button") do %>
          <i class="glyphicon glyphicon-search"></i> <span class="search-shim hidden-xs hidden-sm">Search</span>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoDigitalWith.US</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/favicon.ico' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>

  <%= render 'layouts/footer' %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-82750111-1', 'auto');
    ga('send', 'pageview');
  </script>

  </body>
</html>

app/views/shared/_feed.html.erb
<h2>Popular Tutorials</h2>
<hr class="blue">
<div class="row">
  <% @tutorials.each do |tutorial| %>
    <div class="col-sm-6 feed-card-bottom-margin">
      <%= link_to tutorial, :class => "remove-text-decoration" do %>
        <div class="card card-hover hover">
          <div class="card-text">
            <h3 class="card-title"><%= tutorial.title %></h3>
            <h5 class="tagline"><%= tutorial.tagline %></h5>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/static_pages/contact.html.erb
<div class="content-wrap">
  <div class="container content-margin-bottom">
    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <div class="row tutorial-min">
          <div class="col-sm-12">
            <h2 class="page-title">Contact Us</h2>
            <hr class="blue">
            <p>
              We would love to hear from you. Please send us feedback, questions or let us know it you would like to get involved with this project. Contact us at <a href="mailto:godigitalwithus@gmail.com">godigitalwithus@gmail.com</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/developer.html.erb
<div class="content-wrap">
  <div class="container content-margin-bottom">
    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <h2 class="style-guide">Style Guide</h2>
        <p>To contribute, take a look at our <a href="https://github.com/cmaher92/GoDigitalWithUs" target="_blank">github repo</a>.</p>
        <hr class="blue">

        <h2 class="style-guide">Typography</h2>
        <h4>Merriweather</h4>
        <p>Merriweather is an open source serif font designed to be a text face that is pleasant to read on screens. Currently there are 4 styles: Regular, Light, Bold and Black with Italic styles for each of these weights. Headings (1-5) use Merriweather Bold.</p>
        <h4>Source Sans Pro</h4>
        <p>Source Sans Pro is an open source sans serif font with a variety of weights. All text that does not use Merriweather uses Source Sans Pro.</p>
        <h5>Examples</h5>
        <h1>Here is an H1</h1>
        <h2>Here is an H2</h2>
        <h3>Here is an H3</h3>
        <h4>Here is an H4</h4>
        <h5>Here is an H5</h5>
        <h6>Here is an H6</h6>
        <body>Here is some body text. Here is some body text. Here is some body text. Here is some body text. Here is some body text.</body>
        <p>Here is a p tag. Here is a p tag. Here is a p tag. Here is a p tag. Here is a p tag. Here is a p tag. Here is a p tag.</p>
        <hr class="blue">

        <h2 class="style-guide">Colors</h2>
        <h4>Background Colors</h4>
        <p>There are 3 main colors for backgrounds: primary-dark, gray-lightest and gray-lightest-light. White is not used as a background color.</p>
        <div class="row">
          <div class="col-sm-3 colors-boxes" style="background-color:#112e51"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#f1f1f1"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#eeeeee"><br></div>
        </div>
        <div class="row">
          <div class="col-sm-3 colors-boxes">Primary dark is reserved for the header and footer.</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Gray lightest is used for the main background.</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Gray lightest light is used for card backgrounds.</div>
        </div>
        <h4>Text Colors</h4>
        <p>All text is in the base color, including headings, p tags and body.</p>
        <div class="row">
          <div class="col-sm-3 colors-boxes" style="background-color:#212121"><br></div>
        </div>
        <h4>Link Colors</h4>
        <p>There are links on light and dark backgrounds. Links on light backgrounds change color in the active and hover state. Links on dark backgrounds change color only in the hover state.</p>
        <div class="row">
          <div class="col-sm-3 colors-boxes" style="background-color:#0071bc"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#4c2c92"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#3e94cf"><br></div>
        </div>
        <div class="row">
          <div class="col-sm-3 colors-boxes">Primary is for links on light backgrounds.</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Visit is for links that are in a visited state on light backgrounds.</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Focus is for links that are in the hover state on light backgrounds.</div>
        </div>
        <div class="row">
          <div class="col-sm-3 colors-boxes" style="background-color:#f1f1f1"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#aeb0b5"><br></div>
        </div>
        <div class="row">
          <div class="col-sm-3 colors-boxes">Gray lightest is for links that are in a normal or visited state on a dark background.</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Gray light is for links that are in the hover state on a dark background.</div>
        </div>
        <h4>Secondary Colors</h4>
        <p>Secondary colors may be used on elements that need to stand out.</p>
        <div class="row">
          <div class="col-sm-3 colors-boxes" style="background-color:#e31c3d"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#cd2026"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#981b1e"><br></div>
        </div>
        <div class="row">
          <div class="col-sm-3 colors-boxes">Secondary</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Secondary dark</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Secondary darker</div>
        </div>
        <h4>Tertiary Colors</h4>
        <p>Tertiary colors may be used on elements that need to stand out, but not as much as secondary colors.</p>
        <div class="row">
          <div class="col-sm-3 colors-boxes" style="background-color:#2e8540"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#8ba6ca"><br></div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes" style="background-color:#dce4ef"><br></div>
        </div>
        <div class="row">
          <div class="col-sm-3 colors-boxes">Green</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Cool blue lighter</div>
          <div class="col-sm-offset-1 col-sm-3 colors-boxes">Cool blue lightest</div>
        </div>
        <hr class="blue">

        <h2 class="style-guide">Links</h2>
        <p>Links by default do not have any style. On a light background, When links are in a hover state, the underline will appear and the color will change.</p>
        <h5>Examples</h5>
        <a href="#">This</a> is a link on light background.
        <br>
        <a class="visited" href="#">This</a> is a visited link.
        <div class="row">
          <div class="col-sm-6">
            <div class="dark-background">
              <a href="#">This</a> is a link on a dark background.
            </div>
          </div>
        </div>
        <hr class="blue">

        <h2 class="style-guide">Buttons</h2>
        <p>Buttons should be flat and change color in a hover state.</p>
        <h5>Examples</h5>
        <button class="primary-button">Primary Button</button>
        <br>
        <button class="btn btn-danger">Secondary Button</button>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/guide.html.erb
<div class="content-wrap">
  <div class="container content-margin-bottom">
    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <h2 class="page-title">Tutorial Creation Guide</h2>
        <h3 class="subtitle">How to create a great tutorial</h3>
        <hr class="blue">
        <h4 class="creation-guide">Topic and Title:</h4>

        <p>
          Tutorial topics should cover one topic and one topic only.  The tutorial name should plainly reflect this (e.g. "How to [xxxxxxxx]")  These topics should be a singular task, and should not take the reader more than 1 hour to complete at most.  Larger tutorials should be broken down into multiple topics, so that the reader has natural stopping points to take a break, ask for help, etc.
        </p>

        <h5>Incorrect Title:</h5>

        <p>Email Tutorial</p>

        <h5>Correct Title:</h5>

        <p>Email part 1: How to create an email account</p>
        <p>Email part 2: How to send emails</p>
        <p>Email part 3: How to organize your inbox</p>

        <hr class="blue">
        <h4 class="creation-guide">Tagline Style:</h4>

        <p>
          Try to make the tagline for your tutorial a short, simple sentence explaining the value of knowledge contained in the tutorial.  Do not just reword the title or explain the content--try and contextualize why they should learn this content by explaining why they need to know this information.
        </p>

        <h5>Incorrect Tagline:</h5>
        <p>
          Title: How to create an email account
        </p>

        <p>
          Tagline:  Learn how to sign up for an email account
        </p>

        <h5>Correct Tagline:</h5>
        <p>
          Title: How to create an email account
        </p>

        <p>
          Tagline:  New to the internet?  First thing you'll need is your own email account.  With an email account, you'll be able to keep in touch with friends and family, conduct business, and sign up for all the great things the internet has to offer!
        </p>

        <hr class="blue">
        <h4 class="creation-guide">Tutorial Body:</h4>

        <h5>Introduction</h5>
        <p>
          Your tutorials should start with a brief introduction.  This introduction should briefly cover what they will learn, and why it is important for them to learn it.  Remember, they may still not be fully convinced that this tutorial is worth their time yet!  A strong introduction should convince them that the knowledge within is relevant to their lives, and should give them a brief high-level overview of the steps of the tutorial.  This will make it easier for them to follow along when they actually start reading the content.
        </p>

        <h5>Prerequisites</h5>
        <p>
          Be sure to list any prerequisite knowledge that is essential to the tutorial.  Do they need an email account before starting this tutorial?  Mention that.  Should they be familiar with using word processor software? Mention that too.  It's better to err on the side of caution in this respect, as many new learners will be working through the content of your tutorial.  If they get half way through and realize they aren't ready for this material, they will likely close it and not come back.  By listing prerequisites before they begin, the reader can self-determine if they are ready to begin. If they are not, they should be able to easily search those tutorials and then come back to your tutorial later.
        </p>

        <h5>Content</h5>
        <p>
          Break your tutorials into logical steps.  These are breakpoints for the learner to check their work, take a break, or review what they have just learned.  Examples of a single step be something like whenever they set the settings for something, submit a form, send a message, etc.  If a step seems too large, consider breaking it into smaller steps.
        </p>
        <p>
          Try to include pictures as often as possible, especially when telling the reader to look for/click on something specific.  Be sure to include a disclaimer that the page may look a little different by the time they read this tutorial--that way new learners wont panic if a website has been redesigned and a button has been moved.
        </p>

        <div class="text-right">
          <div class="btn secondary-button">
            <%= link_to "Create Tutorial", "/tutorials/new" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="content-wrap">
  <div class="main-page">
    <div class="container content-margin-bottom">
      <div class="row">
        <div class="col-md-8">
          <div>
            <%= render 'shared/feed' %>
          </div>
        </div>
        <div class="col-md-offset-1 col-md-3 hidden-sm hidden-xs">
          <div class="row right-col">
            <h3>Topics</h3>
            <hr class="blue">
          </div>
          <div class="row">
            <div>
              <h3>
                <i class="glyphicon glyphicon-headphones"></i> 
                Music & Entertainment
              </h3>
              <ol class="list-unstyled">
                <li><a href="/tutorials/15">How to Watch Video Online</a></li>
                <li><a href="/tutorials/16">How to Rent Movies Online</a></li>
                <!-- <li><a href="#">How to Find Fun Games to Play</a></li> -->
              </ol>
            </div>
          </div>
          <div class="row">
            <div>
              <h3>
                <i class="glyphicon glyphicon-thumbs-up"></i> 
                Family & Friends
              </h3>
              <ol class="list-unstyled">
                <li><a href="/tutorials/21">How to Create a Facebook Account</a></li>
                <li><a href="/tutorials/18">How to Create an Email Account</a></li>
                <!-- <li><a href="#">How to Use Different Messaging Apps</a></li> -->
              </ol>
            </div>
          </div>
         <!--  <div class="row">
            <div>
              <h3>
                <i class="glyphicon glyphicon-piggy-bank"></i> 
                Finances & Money
              </h3>
              <ol class="list-unstyled">
                <li><a href="#">How to Create an Online Banking Account</a></li>
                <li><a href="#">How to Find Money Management Apps</a></li>
                <li><a href="#">How to Use Mobile Banking</a></li>
              </ol>
            </div>
          </div> -->
          <!-- <div class="row">
            <div>
              <h3>
                <i class="glyphicon glyphicon-credit-card"></i> 
                Government & Licenses
              </h3>
              <ol class="list-unstyled">
                <li><a href="#">How to Renew Your License</a></li>
                <li><a href="#">How to Apply for EBT/SNAP</a></li>
                <li><a href="#">How to Apply for WIC</a></li>
              </ol>
            </div>
          </div> -->
          <div class="row">
            <div>
              <h3>
                <i class="glyphicon glyphicon-print"></i> 
                Computer Basics
              </h3>
              <ol class="list-unstyled">
                <li><a href="/tutorials/19">How to Use a Mouse</a></li>
                <li><a href="/tutorials/17">What Is a Computer?</a></li>
                <!-- <li><a href="#">How to Use the Keyboard</a></li> -->
                <!-- <li><a href="#">Printing a Document</a></li> -->
              </ol>
            </div>
          </div>
          <div class="row">
            <div>
              <h3>
                <i class="glyphicon glyphicon-globe"></i> 
                Internet Basics
              </h3>
              <ol class="list-unstyled">
                <!-- <li><a href="#">What is the Internet?</a></li> -->
                <!-- <li><a href="#">Different Browsers to Use</a></li> -->
                <li><a href="/tutorials/18">How to Create an Email Account</a></li>
                <li><a href="/tutorials/25">How to Use a Smartphone</a></li>
                <!-- <li><a href="#">How to Store Documents Online</a></li> -->
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tutorials/edit.html.erb
<div class="content-wrap">
  <div class="container content-margin-bottom">
   <div class="col-sm-offset-2 col-sm-8">
    <h2 class="page-title">Editing Tutorial</h2>
    <hr class="blue">
    <div class="row">
      <h3 class="small pull-right">
        <%= link_to 'Back', @tutorial %> | <%= link_to 'All Tutorials', tutorials_path %>
      </h3>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/tutorials/index.html.erb
<div class="content-wrap">
  <div class="container content-margin-bottom"> 
    <div class="col-sm-offset-2 col-sm-8">
      <%= notice %>
    </div>
    <div class="col-sm-offset-2 col-sm-8">
      <div class="row">
        <div class="col-sm-12 card-side-margins">
          <h2 class="page-title">Listing Tutorials</h2>
          <hr class="blue">
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <h3>Title</h3>
        </div>
        <div class="col-sm-3">
          <h3>Created By</h3>
        </div>
      </div>

      <% @tutorials.each do |tutorial| %>
        <div class="row">
          <div class="col-sm-6">
            <%= tutorial.title %>
          </div>
          <div class="col-sm-3">
            <%= tutorial.user.email %>
          </div>
          <div class="col-sm-3">
            <h3 class="small pull-right">
              <%= link_to 'Show', tutorial %> | 
              <%= link_to 'Edit', edit_tutorial_path(tutorial) %> | 
              <%= link_to 'Delete', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %>
            </h3>
          </div>
        </div>
        <hr>
      <% end %>

      <div class="text-right">
        <div class="btn secondary-button">
          <%= link_to "Create Tutorial", "/tutorials/new" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tutorials/show.html.erb
<div class="container content-margin-bottom">

  <div class="row">
    <div class="container">
      <div class="col-sm-offset-2 col-sm-8">
        <div class="row tutorial-min">

          <h2 class="page-title"><%= @tutorial.title %></h2>
          <h3 class="subtitle"><%= @tutorial.tagline %></h3>

          <% if !@tutorial.author.nil? && !@tutorial.author.empty? %>
            <h6 class="byline">Author: <%= @tutorial.author %> </h6>
          <% end %>

          <% if !@tutorial.organization.nil? && !@tutorial.organization.empty? %>
            <h6 class="byline">Organization: <%= @tutorial.organization %> </h6>
          <% end %>
          <hr class="blue">

          <p><%= raw @tutorial.content %></p>

          <% if current_user %>
            <div class="text-right" id="test">
              <h3><small>
                <% if current_user.admin? || current_user.id == @tutorial.user_id %>
                  <%= link_to 'Edit', edit_tutorial_path(@tutorial) %>
                <% end %>
                <% if current_user.admin? || current_user.id == @tutorial.user_id %>
                   | <%= link_to 'Delete', tutorial_path(@tutorial.id),  method: :delete %>
                <% end %>
              </small></h3>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>